name: upload-to-s3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy to'
        required: true
        type: choice
        options:
          - DEV
          - STAGING
          - PROD

permissions:
  contents: read
  id-token: write

jobs:
  upload-to-s3:
    environment:
      name: ${{ inputs.environment || 'DEV'. }}
    name: copy and upload to s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sign into AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: eu-west-1
        
      - name: Verify account
        run: |
          aws sts get-caller-identity

      - name: Upload to s3
        env: 
          S3_BUCKET: ${{ secrets.S3_Bucket }}
        run: aws s3 sync "s3://${ S3_BUCKET }/"



    